# Travis CI script
language: c

os:
- linux
- osx

sudo: false

env:
- BUILD_TYPE=default
- BUILD_TYPE=qt-android
- BUILD_TYPE=check_zproto
- BUILD_TYPE=check_zproject

# Build and check this project according to the BUILD_TYPE
script: ./ci_build.sh
