# Travis CI script
language: java

os:
- linux
- osx

sudo: false

services:
- docker

addons:
  apt:
    packages:
    - git
    - uuid-dev
    - valgrind

env:
  - BUILD_TYPE=default
  - BUILD_TYPE=check_zproto
  - BUILD_TYPE=check_zproject
  - BUILD_TYPE=bindings BINDING=jni

matrix:
  exclude:
  - env: BUILD_TYPE=bindings BINDING=jni
    os: osx
  # osx environment does not have docker
  - os: osx
    env: BUILD_TYPE=check_zproto
  - os: osx
    env: BUILD_TYPE=check_zproject

# Build and check this project according to the BUILD_TYPE
script: ./ci_build.sh
